apiVersion: apps/v1
kind: Deployment
metadata:
  name: Concert
  labels:
    app: Concert
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Concert
  template:
    metadata:
      labels:
        app: Concert
    spec:
      containers:
        - name: Concert
          image: username/Concert:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5